### ISSUE TITLE
Versioning behavior is broken for "File" type

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.versioningbehavior#14]
After adding versioning behavior to ```File``` type (configuring versioning in control panel "Types" as well) and adding a File within a folder and saving it, I get:

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 112, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.add, line 99, in handleAdd
  Module z3c.form.form, line 247, in createAndAdd
  Module plone.dexterity.browser.add, line 78, in add
  Module plone.dexterity.utils, line 179, in addContentToContainer
  Module OFS.ObjectManager, line 359, in _setObject
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module plone.app.versioningbehavior.subscribers, line 62, in create_version_on_save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 305, in save
  Module Products.CMFEditions.CopyModifyMergeRepositoryTool, line 451, in _recursiveSave
  Module Products.CMFEditions.ArchivistTool, line 265, in prepare
  Module Products.CMFEditions.ModifierRegistryTool, line 143, in getReferencedAttributes
  Module Products.CMFEditions.StandardModifiers, line 1170, in getReferencedAttributes
AttributeError: Schema
```

I even tested with the last versions of plone.app.versioningbrhavior (1.2.2) and Products.CMFEditions (2.2.13) but the error persists.

**Comment by rafaelbco** [comment]
Is the File type mentioned from ATContentTypes or plone.app.contenttypes ?
What is the Plone version ?


Rafael Oliveira

**Comment by idgserpro** [comment]
plone.app.contenttypes 1.0, Products.CMFPlone 4.3.3.

**Comment by rafaelbco** [comment]
Well, looking at the code it seems versioning for blob fields in Dexterity
content types was never implemented. Can anyone confirm that ?


Rafael Oliveira

**Comment by rafaelbco** [comment]
Forget my last comment. Versioning of blob fields for Dexterity is
implemented, the Changelog for plone.app.versioningbehavior says so.

Please try this workaround:

Go to the ZMI, on the path
"/your-plone-site/portal_modifier/CloneBlobs/manage_workspace". Disable
this modifier and save. Then try again.

Please report the results.



Rafael Oliveira

**Comment by idgserpro** [comment]
Indeed, it works. What exactly am I losing by disabling CloneBlobs?

**Comment by rafaelbco** [comment]
Nothing, I guess. There's another modifier called CloneNamedBlobFiles which
works for Dexterity content types. So you have to disable the old
CloneBlobs and enable the new one CloneNamedBlobFiles.

We need to solve this somehow, but I can't work in this right now.


Rafael Oliveira

**Comment by idgserpro** [comment]
Ok, at least there's a workaround. Thanks for the fast response.

**Comment by rafaelbco** [comment]
Fixed by [this commit on Products.CMFEditions](https://github.com/plone/Products.CMFEditions/commit/fb2ded6fd3ea9f0a7f3d9c0161bba929191bf486)
