### ISSUE TITLE
What are the supported Plone versions?

### ISSUE THREAD

**Issue by rafaelbco** [plone/plone.app.versioningbehavior#23]
I'm assuming Plone >= 4.3.x, am I correct? Should we put it on the README? Is there a general policy about this written some where? So many questions ... :smile: 

@mauritsvanrees, could you help me out? I'm trying to fix a bug and this question came up.

**Comment by mauritsvanrees** [comment]
For some packages it is anyone's guess...
If it's not in the readme, then you can look in two places:

- The classifiers in `setup.py`: they say Plone 5.
- The versions.cfg and sources.cfg in the coredev buildout branches. coredev 5.0 and 5.1 use version 1.2.7 and the master branch. coredev 4.3 is still at 1.2.0 and does not have it in the sources.cfg: it is not officially part of core there.

When looking at `CHANGES.rst` it does not look like there are any changes that would fail on 4.3. So for any changes you plan, it would be nice if it not only works on Plone 5, but also 4.3.
You can forget about Plone 4.2 or lower: 4.2.7 pins version 1.1.

If you run into too many problems getting a change to work in Plone 4.3, it is fine to target Plone 5 only: we can create a 1.2.x branch that remains compatible with Plone 4.3 and continue development with your changes on the master branch.

**Comment by rafaelbco** [comment]
Thanks!
