### ISSUE TITLE
@@types-controlpanel missing in Plone 5

### ISSUE THREAD

**Issue by andreesg** [plone/plone.app.versioningbehavior#33]
While trying to enable the versioning behavior for a custom dexterity type by following:
* "You have to set the "versioning" option in the Plone types control panel (/@@types-controlpanel) to either "Manual" or "Automatic" for activating versioning."

Found that the @@types-controlpanel view is no longer available in Plone 5, therefore it is not possible to change the versioning from Manual to Automatic TTW

Any ideas what is the problem?

**Comment by jaroel** [comment]
I think it's called "Content Settings" (@@content-controlpanel) nowadays?

**Comment by jaroel** [comment]
And don't forget to add 'plone.versions' to the behaviors.

**Comment by idgserpro** [comment]
@jaroel please check https://github.com/plone/Products.CMFPlone/issues/2148#issuecomment-422868200 for a discussion about this matter.
