### ISSUE TITLE
Locales moved to plone.app.locales broke branch 4.3.x

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.versioningbehavior#40]
The translation for `help_change_note` is available in https://github.com/collective/plone.app.locales/blob/0befd57b8a9c1a7cd140a4688eb2f330947ba001/plone/app/locales/locales/en/LC_MESSAGES/plone.po#L8724 but not in [4.3 branch](https://github.com/collective/plone.app.locales/blob/119b0d33c65b870deb1a1c4b08c8f2c046d6cd20/plone/app/locales/locales/en/LC_MESSAGES/plone.po). The translation in 5.0.x is not the same as the `default` option

This bug was added when doing https://github.com/plone/plone.app.versioningbehavior/issues/19

**Comment by gforcada** [comment]
Plone 5.0.x and 4.3 are no longer supported, is this also affecting upstream? 🤔 

Hopefully not 🍀 re-open if otherwise!
