### ISSUE TITLE
blob creation is too aggressiv

### ISSUE THREAD

**Issue by iham** [plone/plone.app.versioningbehavior#42]
https://github.com/plone/plone.app.versioningbehavior/blob/master/plone/app/versioningbehavior/modifiers.py#L174

```python
field.get(iface(obj))._blob = blob
````
is too aggressive for my usecase and so i want to reformulate it to this:
```python
adapted_field = field.get(iface(obj))
if adapted_field:
    adapted_field._blob = blob
```

**Comment by ale-rt** [comment]
I think this was fixed in #43. Reopen if I am wrong
