### ISSUE TITLE
Unauthorized exception on save without permission "CMFEditions: Access previous versions"

### ISSUE THREAD

**Issue by mbarde** [plone/plone.app.versioningbehavior#46]
If a user, who has not the permission `CMFEditions: Access previous versions`, tries to create / save an object with versioning behavior enabled an `Unauthorized` exception is raised here: [see](https://github.com/plone/plone.app.versioningbehavior/blob/master/plone/app/versioningbehavior/modifiers.py#L116)

This is because `retrieve` method of the CopyModifyMergeRepositoryTool asserts this permission is given ([see](https://github.com/plone/Products.CMFEditions/blob/master/Products/CMFEditions/CopyModifyMergeRepositoryTool.py#L409)).

I think this is a bug since a user should be able to edit content even if he is not allowed to access previous versions of it.

Could be fixed by catching `Unauthorized` here as well: [see](https://github.com/plone/plone.app.versioningbehavior/blob/master/plone/app/versioningbehavior/modifiers.py#L117)

Or maybe there is a not so strict alternative to the `retrieve` method of the CopyModifyMergeRepositoryTool?

**Comment by davisagli** [comment]
This may be fixed by #67 since that changes the implementation so that retrieving old versions is no longer necessary.

**Comment by gforcada** [comment]
@mbarde could you confirm that #67 fixes it?

Hopefully it does 🍀 so I'm closing it. Re-open otherwise!
