### ISSUE TITLE
Traceback with download link transformation

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.versioningbehavior#51]
https://github.com/plone/plone.app.versioningbehavior/blob/86c34b65063be40707e1d854f2b4d17795ef251e/plone/app/versioningbehavior/browser.py#L107

The default value (`IPrimaryFieldInfo(self.context).fieldname`) is always calculated (even if `field_id` is in `request`), and can lead to this traceback :
```
  Module plone.app.versioningbehavior.browser, line 108, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.dexterity.primary, line 25, in __init__
TypeError: ('Could not adapt', <MyContent at /plone/my-content>, <InterfaceClass plone.rfc822.interfaces.IPrimaryFieldInfo>)
```

**Comment by ericof** [comment]
Closed by #52
